name: Spellcheck

on:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
        